Controllers/AdminController.cs
using ProiectFinalASP.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using Encryption;
using System.Web.Management;

namespace ProiectFinalASP.Controllers
{
    public class AdminController : Controller
    {
        //basic index view
        public ActionResult Index()
        {
            return View();
        }

        //Add to cart method. When entering by pressing a buy button,
        //passes id of item. When accesed form layout.cshtml, id gets
        //passed as 0 and no item is added
        public ActionResult AddToCart(int id)
        {
            if (id == 0)
            {
                using (ItemContext idb = new ItemContext())
                {
                    return View(idb.Carts.ToList());
                }
            }
            else
                using (ItemContext idb = new ItemContext())
                {
                    Item item = idb.Items.Find(id);
                    Cart c = new Cart();

                    c.itemName = item.Name;
                    c.itemPrice = item.Price;
                    c.itemImageUrl = item.ImageUrl;

                    idb.Carts.Add(c);
                    idb.SaveChanges();

                    return View(idb.Carts.ToList());
                }
        }

        //simple account page for logging in
        public ActionResult Account()
        {
            return View();
        }
        //simple account page for registering
        public ActionResult Account2()
        {
            return View();
        }
        //Criptarea datelor - contributia lui Joldes/*
        static RijndaelManaged rijndael = new RijndaelManaged();
        /*static byte[] EncryptString(string plainText)
        {
            byte[] plainTextBytes = System.Text.Encoding.UTF8.GetBytes(plainText);
            using (MemoryStream ms = new MemoryStream())
            using (CryptoStream cs = new CryptoStream(ms, rijndael.CreateEncryptor(), CryptoStreamMode.Write))
            {
                cs.Write(plainTextBytes, 0, plainTextBytes.Length);
                cs.FlushFinalBlock();
                byte[] cipherTextBytes = ms.ToArray();
                return cipherTextBytes;
            }
        }*/
        //Criptarea datelor - contributia lui Joldes

        //Http action result, when button is pressed check if account exists 
        //and logs in user by using static class credentials, and ecrypting the password
        //using the Assembly .dll Encryption
        [HttpPost]
        public ActionResult AccountCheck(string name, string password)
        {
            using (ItemContext idb = new ItemContext())
            {
                foreach (var user in idb.Users)
                {
                    //Criptarea datelor - contributia lui Joldes
                    rijndael.KeySize = 256;
                    rijndael.BlockSize = 256;
                    rijndael.GenerateKey();
                    rijndael.GenerateIV();
                    //Criptarea datelor - contributia lui Joldes

                    //Validarea datelor de intrare in AccountCheck - contributia lui Joldes
                    if (name.Length < 3)
                    {
                        return Json("Username has too few characters");
                    }
                    else if (password.Length < 3)
                    {
                        return Json("Password has too few characters");
                    }
                    else if(name.Length < 3 && password.Length < 3)
                    {
                        return Json("Error logging, username and password have too few characters");
                    }
                    //Validarea datelor de intrare in AccountCreate - contributia lui Joldes

                    if (user.Username == name && user.Password == password)//Validare daca exista name si password in baza de date
                    {
                        //Criptarea datelor - contributia lui Joldes
                        byte[] encryptPassword = Encryption.Encryption.EncryptString(password);
                        Credentials.LoggedinPassword = encryptPassword;
                        Credentials.LoggedinUsername = name;
                        //Criptarea datelor - contributia lui Joldes
                        Credentials.IsLoggedIn= true;
                        return Json("Succesfully logged in");
                    }
                }
            }
            return Json("Wrong username or password");
        }

        [HttpPost]// Functie care creeaza un cont bazat pe user input, si il adauga la baza de date ItemContext.users
        public ActionResult AccountCreate(string name, string password)
        {
            using (ItemContext idb = new ItemContext())
            {
                //Validarea datelor de intrare in AccountCreate - contributia lui Joldes
                if (name.Length >= 3 && password.Length >= 3)
                {
                    return Json("User was registered");
                }
                else if (name.Length < 3)
                {
                    return Json("Username has too few characters");
                }
                else if (password.Length < 3)
                {
                    return Json("Password has too few characters");
                }
                else if (name.Length < 3 && password.Length < 3)
                {
                    return Json("Error registering, username and password have too few characters");
                }
                //Validarea datelor de intrare in AccountCreate - contributia lui Joldes

                foreach (var user in idb.Users)
                {
                    if (user.Username == name)
                        return Json("Username is taken");
                }

                User u = new User();
                u.Username = name;
                u.Password = password;

                idb.Users.Add(u);
                idb.SaveChanges();
            }
            return Json("Account succesfully created");
        }
    }
}

Controllers/StoreController.cs
using ProiectFinalASP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace ProiectFinalASP.Controllers
{
    public class StoreController : Controller
    {
        public ActionResult Index() // Store index view method that shows all available products
        {
            using (ItemContext idb = new ItemContext())
            {
                /*
                Item i = new Item();            //code used to add new items at runtime

                i.Name = "Wing Trousers";
                i.ImageUrl = "Pants2.png";
                i.Price = 999;
                i.Type = "Pants";

                idb.Items.Add(i);
                idb.SaveChanges();*/

                var model = idb.Items.ToList(); //Converts all items to a list
                return View(model); //sends list of items to store index view
            }
        }

        [HttpPost]//Code for when a cart purchase is succesful
        public ActionResult Confirm()
        {
            using (var db = new ItemContext())
            {
                db.Database.ExecuteSqlCommand("DELETE FROM Carts");
                //db.SaveChanges();
            }

            return Json("Confirmed Purchase");
        }
    }
    
}

Views/Admin/Account.cshtml
@model ProiectFinalASP.Models.User

@{
    ViewBag.Title = "Login";
}

<h2>Log in</h2>

<html>
<body>
    <style>
        td {
            padding: 40px;
        }
    </style>
    <!-- Form that takes some text and a password, sends it to the below script using a button-->
    <form id="myForm">
        <input type="text" id="txtName" name="name" placeholder="Enter your name" required>
        <input type="password" id="txtPassword" name="password" placeholder="Enter your password" required>
        <button type="submit">Submit</button>
    </form>

</body>
</html>

@section scripts{<!-- Script section, takes data from myForm, sends the data to AccountCheck actionresult method in the AdminController class-->
    <script>     
        $(document).ready(function () {
            $("#myForm").submit(function (e) {
                e.preventDefault();
                var name = $("#txtName").val();
                var password = $("#txtPassword").val();

                $.ajax({
                    type: "POST",
                    url: "@Url.Action("AccountCheck", "Admin")",
                    data: { name: name, password: password },
                    success: function (data) {
                        // Handle the response
                        alert(data);
                    },
                    error: function (xhr, status, error) {
                        // Handle the error
                        alert(error);
                    }
                });
            });
        });
    </script>
}

Views/Admin/Account2.cshtml
@model ProiectFinalASP.Models.User

@{
    ViewBag.Title = "Login";
}

<h2>Register</h2>

<html>
<body>
    <style>
        td {
            padding: 40px;
        }
    </style>
    <!-- Form that takes some text and a password, sends it to the below script using a button-->
    <form id="myForm">
        <input type="text" id="txtName" name="name" placeholder="Enter your name" required>
        <input type="password" id="txtPassword" name="password" placeholder="Enter your password" required>
        <button type="submit">Submit</button>
    </form>

</body>
</html>

@section scripts{
    <script>
        $(document).ready(function () {
            $("#myForm").submit(function (e) {
                e.preventDefault();
                var name = $("#txtName").val();
                var password = $("#txtPassword").val();

                $.ajax({
                    type: "POST",
                    url: "@Url.Action("AccountCreate", "Admin")", //Sends the relevant data to AccountCreate actionresult method in AdminController
                    data: { name: name, password: password },
                    success: function (data) {
                        // Handle the response
                        alert(data);
                    },
                    error: function (xhr, status, error) {
                        // Handle the error
                        alert(error);
                    }
                });
            });
        });
    </script>
}

Views/Admin/AddToCart.cshtml
@using ProiectFinalASP.Models;

@model IEnumerable<ProiectFinalASP.Models.Cart>

@{
    ViewBag.Title = "ShoppingCart";
}

@if (Credentials.IsLoggedIn == true)
{
    <!-- Sow login username-->
    <h2>Logged in as @Credentials.LoggedinUsername</h2>
    <html>
    <body>
        <style>
            td {
                padding: 40px;
            }
        </style>
        <table><!-- Create table and add columns-->
            <thead>
                <tr>
                    <th>Product name</th>
                    <th>Product price</th>
                    <th>Product image</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model) //Go trough each item in carts database, and show item price and image
                {
                    <tr>
                        <td>@item.itemName</td>
                        <td>@item.itemPrice</td>
                        <td>
                            <img src="@Url.Content("~/Images/")@item.itemImageUrl" alt="Image" width="50" height="50">
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <form id="myForm"><!-- Add button to confim cart purchase-->
            <button type="submit">Confirm Purchase</button>
        </form>
    </body>
</html>
}
else
{
<h1>Log in to see shopping cart</h1>
}

@section scripts{   
    <script>
        $(document).ready(function () {
            $("#myForm").submit(function (e) {
                e.preventDefault();

                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Confirm", "Store")", //Receive button data and send it to the Confirm method in the StoreController
                    success: function (data) {
                        // Handle the response
                        alert(data);
                    },
                    error: function (xhr, status, error) {
                        // Handle the error
                        alert(error);
                    }
                });
            });
        });
    </script>
}